name: Lint

on: [pull_request]

jobs:
  squash:
    name: Check commits count
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check commits count
        run: |
		      if [ "$(git rev-list --count "${GITHUB_REF}" "^${GITHUB_BASE_REF}")" -gt 1 ]; then
					  echo "Please squash"
						return 1
					end
